export const termsLocale = {
  termsDisclaimerTitle: "Disclaimer",
  termsDisclaimerText:
    "© 2022 AtlanticPartners Investments Fund. This information has been obtained from sources believed reliable. We have not verified it and make no guarantee, warranty or representation about it. Any projections, opinions, assumptions or estimates used are for example only and do not represent the current or future performance of the property. You and your advisors should conduct a careful, independent investigation of the property to determine to your satisfaction the suitability of the property for your needs.",
  termsOfUseTitle: "Terms of Use",
  termsOfUse:
    "This AtlanticPartners Investments Fund Terms of Use agreement (this “agreement”) is a legal agreement between you and AtlanticPartners Investments Fund (“AtlanticPartners Investments Fund”, “we”, “us” or “our”) providing, among other things, the terms and conditions for your use of our website accessible at https://www…. (the “site”). {br} {br}We may from time to time modify these Terms of Use and will post a copy of the amended agreement at https://www. If you do not agree to, or cannot comply with, the agreement as amended, you should not use the site. You will be deemed to have accepted the agreement as amended if you continue to use the site after any amendments are posted on the site. We reserve the right to refuse to provide our products and services to anyone at any time. {br} {br}This agreement contains warranty and liability disclaimers. By using this site, you accept and agree to the terms and conditions of this agreement without any reservations, modifications, additions, or deletions. If you do not agree to the Terms of Use contained in this agreement, you are not authorized to use the site. You may be denied access to the site, with or without prior notice to you if you do not comply with any provision of this agreement.",
  authorizedUsersTitle: "1. Authorized users",
  authorizedUsers:
    "1.1 Age requirement; authority. In order to use the site, you must be at least 18 years of age. You represent that (i) you have read and understood, and that you agree to be bound by, this agreement and (ii) you are at least 18 years old. If you do not agree to, or cannot comply with, any of these terms and conditions of this agreement, please do not attempt to access this site.",
  licenseToUseTitle: "2. License to use the site",
  licenseToUse:
    "2.1 Grant of license. AtlanticPartners Investments Fund grants to you a limited, non-exclusive, non-transferable license to access and use the site in accordance with the terms and conditions set forth in this agreement. AtlanticPartners Investments Fund reserves all right, title and interest not expressly granted under this license to the fullest extent possible under applicable laws. Any use of the site not specifically permitted under this agreement is strictly prohibited. {br} {br} 2.2 Restrictions. You agree that you will not: (i) use the site to reproduce, transmit, display or distribute copyrighted material in any medium or via any method without AtlanticPartners Investments Fund’s express written permission; (ii) copy, store, edit, change, prepare any derivative work of or alter in any way any of the content provided on this site; or (iii) use our site in any way that violates the terms of this agreement. The site is owned by AtlanticPartners Investments Fund and is protected by copyright laws and international treaty provisions. You will not sublicense, assign, or transfer the license granted to you under this agreement. Any attempt to sublicense, assign, or transfer any of the rights, duties, or obligations in violation of the provisions of this agreement is void.",
  otherRestrictionsTitle: "3. Other restrictions",
  otherRestrictions:
    "You agree that you will not: (a) impersonate any person or entity or misrepresent your affiliation with any other person or entity; (b) engage in spamming, flooding, harvesting of e-mail addresses or other personal information, spidering, screen scraping, database scraping, or any other activity with the purpose of obtaining lists of users or any other information, including specifically, property listings available through the site; (c) send chain letters or pyramid schemes via the site; or (d) attempt to gain unauthorized access to other computer systems through the site. You agree that you will not use the site in any manner that could damage, disable, overburden, or impair the site or interfere with any other party’s use and enjoyment of the site.",
  copyrightsAndOtherTitle: "4. Copyrights and other intellectual property",
  copyrightsAndOther:
    "4.1 As between you and AtlanticPartners Investments Fund, you acknowledge that AtlanticPartners Investments Fund owns or has a license to all title and copyrights in and to the content provided on this site. All title and intellectual property rights in and to any licensed content provided on this site is the property of the respective content owners and may be protected by applicable copyright or other intellectual property laws and treaties and subject to use restrictions under such laws or treaties. {br} {br} 4.2 Photos herein are the property of their respective owners and use of these images without the express written consent of the owner is prohibited.",
  trademarksAndThirdTitle: "5. Trademarks and third-party trademarks",
  trademarksAndThird:
    "The following are registered trademarks or trademarks of AtlanticPartners Investments Fund: AtlanticPartners Investments Fundand its design logo, as well as certain other AtlanticPartners Investments Fund trademarks, service marks, graphics, and logos (collectively, the “AtlanticPartners Investments Fund trademarks”) used in connection with AtlanticPartners Investments Fund’s provision of products and services. The site may contain third-party trademarks, service marks, graphics, and logos. You are not granted any right or license with respect to the AtlanticPartners Investments Fund trademarks or the trademarks of any third party.",
  privacyPolicyTitle: "6. Privacy policy",
  privacyPolicy:
    " Unless otherwise addressed in this agreement, your use of this site is subject to AtlanticPartners Investments Fund’s privacy policy, which is incorporated by reference and made a part of this agreement. It is important that you read and understand the terms of AtlanticPartners Investments Fund’s privacy policy. AtlanticPartners Investments Fund may cooperate with and disclose information (including your account information) to any authority, government official or third-party, without giving any notice to you, in connection with any investigation, proceeding or claim arising from an asserted illegal action or infringement whether related or unrelated to your use or misuse of this site.",
  submissionsInformationTitle: "7. Submissions or other information",
  submissionsInformation:
    " Unless otherwise addressed in this agreement, your use of this site is subject to AtlanticPartners Investments Fund’s privacy policy, which is incorporated by reference and made a part of this agreement. It is important that you read and understand the terms of AtlanticPartners Investments Fund’s privacy policy. AtlanticPartners Investments Fund may cooperate with and disclose information (including your account information) to any authority, government official or third-party, without giving any notice to you, in connection with any investigation, proceeding or claim arising from an asserted illegal action or infringement whether related or unrelated to your use or misuse of this site.",
  term8Title: "8. Term",
  term8:
    "This agreement will remain effective until terminated by you or terminated by us.",
  disclaimerTitle: "9. Disclaimers",
  disclaimer:
    "9.1 The site (including all of its content) is provided to you “as is.” Any use of this site is at your own risk. To the maximum extent permitted by applicable law, AtlanticPartners Investments Fund disclaims all warranties, either express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, title and non-infringement. AtlanticPartners Investments Fund makes no representations, warranties or guarantees that this site will be free from loss, destruction, damage, corruption, attack, viruses, interference, hacking, or other security intrusion, and AtlanticPartners Investments Fund disclaims any liability relating thereto. {br} {br}9.2 AtlanticPartners Investments Fund makes no representations, warranties or guarantees that use or results of the use of the site (including all of its content) is or will be accurate, reliable, current, uninterrupted or without errors. Without prior notice, AtlanticPartners Investments Fund may modify, suspend, or discontinue any aspect or feature of this site or your use of this site. If AtlanticPartners Investments Fund elects to modify, suspend, or discontinue the site, it will not be liable to you or any third party. {br} {br} 9.3 All property listing information contained within this site is subject to the possibility of errors, omissions, change of price, rental or other conditions, prior sale, lease or financing, or withdrawal without notice. Any projections, opinions, assumptions or estimates contained within this site are for example only, and such projections, opinions, assumptions or estimates may not represent current or future performance of a listed property. You and your tax and legal advisors should conduct your own investigation of any property listed on this site and any contemplated transaction concerning any property listed on this site. {br} {br} 9.4 You acknowledge that your submission of any information to us is at your own risk. AtlanticPartners Investments Fund does not assume any liability to you with regard to any loss or liability relating to such information in any way. {br} {br} 9.5 Some of the content, products, and services available through the AtlanticPartners Investments Fund site may include materials that belong to third parties. You acknowledge that AtlanticPartners Investments Fund assumes no responsibility for such content, products or services.",
  limitationLiabilityTitle: "10. Limitation of liability",
  limitationLiability:
    "In no event will AtlanticPartners Investments Fund be liable to you for indirect, general, special, incidental, consequential, exemplary or other damages (including, without limitation, damages for loss of profits, business interruption, corruption of files, loss of business information or any other pecuniary loss) even if AtlanticPartners Investments Fund has been advised of the possibility of such damages. No oral or written information or advice given by AtlanticPartners Investments Fund or others will create a warranty and neither you nor any third party may rely on any such information or advice. Some jurisdictions do not allow the exclusion of implied warranties or limitation or exclusion of liability for incidental or consequential damages, so the above exclusions and limitations may or may not apply to you.",
  indemnityTitle: "11. Indemnity",
  indemnity:
    "You will indemnify and hold AtlanticPartners Investments Fund, its directors, officers, employees, affiliates, agents, contractors, and licensors harmless with respect to any suits or claims arising out of (i) your breach of this agreement, including, but not limited to, any infringement by you of the copyright or intellectual property rights of any third party; or (ii) your use or misuse of the site.",
  generalTermsTitle: "12. General",
  generalTerms:
    "12.1 You will be responsible for providing the dial-up, DSL, cable modem or other form of Internet access and any other hardware and software necessary to access and use the site. {br} {br} 12.2 AtlanticPartners Investments Fund complies with all applicable laws, including, but not limited to, privacy laws and individual state laws with respect to the sale or lease of real property. You agree that you will comply with all such laws applicable to you. {br} {br} 12.3 AtlanticPartners Investments Fund or its business partners may present advertisements or promotional materials on or through the site. Your dealings with, or participation in promotions of, any third-party advertisers on or through the site are solely between you and such third party and your participation is subject to the terms and conditions associated with that advertisement or promotion. You agree that AtlanticPartners Investments Fund is not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such third party materials on the site. {br} {br} 12.4 If you know of, or suspect, copyright infringement, please send a notice to AtlanticPartners Investments Fund; Address: Calea Floreasca 165, etaj 6 One Tower, Sector 1 Bucharest 014459. {br} {br} 12.5 This agreement will be governed by the laws of the (…). The exclusive jurisdiction for any claim, action or dispute with AtlanticPartners Investments Fund or relating in any way to your use of the site will be in the state and federal courts of the (…) and the venue for the adjudication or disposition of any such claim, action or dispute will be in the (…).",
};
